# Generated by Django 4.1.3 on 2022-11-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('chat_function', models.BooleanField(default=False)),
                ('user_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LIKED', to='accounts.profile')),
                ('user_liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LIKER', to='accounts.profile')),
            ],
        ),
    ]
