# Generated by Django 4.1.3 on 2022-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesmodel',
            name='user_liked_like',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='matchesmodel',
            name='user_liker_like',
            field=models.BooleanField(default=None),
        ),
    ]
