# Generated by Django 4.1.3 on 2022-11-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='profile',
        ),
    ]
