# Generated by Django 4.1.3 on 2022-11-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
