# Generated by Django 4.1.3 on 2022-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customusermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
